Parameters:
  DeploymentBucketName:
    Description: Name of the S3 bucket used by SAM during deploy
    Type: String

Resources:
  SamS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref DeploymentBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
